### ISSUE TITLE
[Inquiry] International Market mechanics usability (AAT DLC)

### ISSUE THREAD

**Issue by PPsyrius** [1230james/hoi4-ammunition#1]
I'm sorry to ask this here, but the Steam Workshop page has no comment section available - if not though, I would be happy to contribute to get them working for this mod.

**Comment by 1230james** [comment]
Pretty sure comments are available on the workshop page

You currently can't sell ammo on the market; ammo exists only has a bunch of numbers in memory and the game otherwise has no concept of it.

AFAIK you can only put equipment on the market so I'm not exactly sure if it'd even be possible to implement the ability to sell ammo?
